ls()
rm(list=ls())
gc()


a=4  # shape parameter
b=2  # scale parameter


set.seed(1020)
x=rgamma(10000,a,1/b)

N=10000
x1 = rep(0, N) # the sampled points
x1[1]=2.5

for (n in 2:N)
{
  x2=x1[n-1]
  
  u=runif(1, min=0, max=1)*x2^(a-1)
  
  left=u^(1/(a-1))
  
  
  u2=runif(1, min=0, max=1)*exp(-x2/b)
  
  right=-b*log(u2)
  
  x1[n]=runif(1, min=left, right)
}

#dev.off()
#graphics.off()
par(mar=c(4,4,4,4))
par(mfrow=c(2,1))

hist(x1, prob=TRUE,
     main="Histogram of samples generated by slice sampling",
     border="red",  
     col="blue",
     xlim=c(0,25)) # prob=TRUE for probabilities not counts
densitykernel= density(x1) 
lines(densitykernel,
      lty=5,
      lwd=4,
      col="red")# add a density estimate with defaults
# lines(density(x, adjust=2), lty="dotted")  # add another "smoother" density

hist(x, prob=TRUE,
     main="Histogram of samples generated by using R rgamma function",
     border="red",  
     col="blue",
     xlim=c(0,25)) # prob=TRUE for probabilities not counts
densitykernel= density(x) 
lines(densitykernel,
      lty=5,
      lwd=4,
      col="red")# add a density estimate with defaults
# lines(density(x, adjust=2), lty="dotted")  # add another "smoother" density

