ls()
rm(list=ls())
gc()


v = 10# degrees of freedom

set.seed(1020)

N=100000
x=rt(N,v)


x1 = rep(0, N) # the sampled points
x1[1]=0

for (n in 2:N)
{
  x2=x1[n-1]
  
  u=runif(1, min=0, max=1)*(1+ x2^2/v)^(-(v+1)/2)
  
  left=-sqrt( (u^(-2/(v+1)) -1)*v)
  
  
  
  right=sqrt( (u^(-2/(v+1)) -1)*v)
  
  x1[n]=runif(1, min=left, right)
}

#dev.off()
#graphics.off()
par(mar=c(4,4,4,4))
par(mfrow=c(2,1))

hist(x1, prob=TRUE,
     main="Histogram of samples generated by slice sampling",
     border="red",  
     col="blue",
     xlim=c(-3,3),
     ylim=c(0,0.4)
     ,breaks=30) # prob=TRUE for probabilities not counts
densitykernel= density(x1) 
lines(densitykernel,
      lty=5,
      lwd=4,
      col="red")# add a density estimate with defaults
# lines(density(x, adjust=2), lty="dotted")  # add another "smoother" density




hist(x, prob=TRUE,
     main="Histogram of samples generated by using R Student-t function",
     border="red",  
     col="blue",
     xlim=c(-3,3),
     ylim=c(0,0.4)
     ,breaks=30)  # prob=TRUE for probabilities not counts
densitykernel= density(x) 
lines(densitykernel,
      lty=5,
      lwd=4,
      col="red" )# add a density estimate with defaults
# lines(density(x, adjust=2), lty="dotted")  # add another "smoother" density

